"""
Shift Database Model

Represents a single work shift for a gig economy worker.
Maps to the 'shifts' table in PostgreSQL database.
Stores actual earnings, predicted earnings, and supports income guarantee calculations.

Schema mapping:
    Python Class: Shift
    Database Table: shifts
    Inheritance: Inherits from Base (SQLAlchemy declarative base)
\"\"\"
from sqlalchemy import Column, Integer, ForeignKey, DateTime, Float, func
from sqlalchemy.orm import relationship

from src.database import Base


class Shift(Base):
    \"\"\"
    Shift ORM Model - Database representation of a work shift.
    
    Each shift records:
    - Which worker worked this shift
    - When they worked (start_time, end_time)
    - How much they earned (earnings)
    - How much was predicted they could earn (predicted_earnings)
    - Income guarantee: top-up = max(0, predicted×0.9 - earnings)
    
    Database Table: shifts
    Example rows:
        id=1 | worker_id=1 | start_time=2026-02-12 08:00 | end_time=2026-02-12 16:00
        earnings=85.50 | predicted_earnings=95.00 | created_at=2026-02-12...
    
    Relationships:
        Many Shifts belong to one Worker (many-to-one)
        Access via: shift.worker → returns the Worker object
        Reverse: worker.shifts → returns all shifts for that worker
    \"\"\"
    __tablename__ = \"shifts\"

    # ========================================================================
    # DATABASE COLUMNS
    # ========================================================================
    
    # PRIMARY KEY - Uniquely identifies each shift
    # Auto-incremented: 1, 2, 3, ...
    # index=True: Database index for fast lookups
    id = Column(Integer, primary_key=True, index=True)
    
    # FOREIGN KEY - Link to workers table
    # Stores the ID of the worker who worked this shift
    # ForeignKey(\"workers.id\"): References workers.id column
    # Enforces referential integrity: worker_id must exist in workers table
    # nullable=False: Every shift must belong to a worker (no orphan shifts)
    # index=True: Create index for fast worker lookups
    # Used for: Identifying shift owner, querying shifts by worker
    worker_id = Column(Integer, ForeignKey(\"workers.id\"), nullable=False, index=True)
    
    # SHIFT START TIME - When the shift began
    # DateTime: Date and time with precision
    # nullable=False: Start time is required (all shifts must have start_time)
    # Used for: Calculating shift duration, sorting shifts chronologically
    start_time = Column(DateTime, nullable=False)
    
    # SHIFT END TIME - When the worker stopped working
    # DateTime: Date and time
    # nullable=True: Can be null for ongoing/incomplete shifts
    # Null value means: Shift is still in progress, not ended yet
    # Used for: Calculating shift duration, marking completion
    end_time = Column(DateTime, nullable=True)
    
    # ACTUAL EARNINGS - Money earned during this shift
    # Float: Decimal number (supports cents: 45.75)
    # default=0.0: If not provided, defaults to zero earnings
    # This is the real amount the worker received from the platform
    # Used for: Income tracking, top-up calculation
    earnings = Column(Float, default=0.0)
    
    # PREDICTED EARNINGS - ML model's estimate for this shift
    # Float: Decimal number (machine learning model output)
    # default=0.0: Defaults to zero if no prediction available
    # Generated by: EarningsPredictor ML model based on time, location, demand
    # Used for: Income guarantee calculation, performance evaluation
    # Top-up formula: max(0, predicted_earnings × 0.9 - earnings)
    # Example: predicted=100, earnings=80, guarantee=max(0, 90 - 80) = 10 top-up
    predicted_earnings = Column(Float, default=0.0)
    
    # CREATION TIMESTAMP - When this shift record was created
    # DateTime: Date and time
    # server_default=func.now(): PostgreSQL sets timestamp automatically
    # No manual input needed - automatically set when record created
    # Used for: Record creation tracking, data auditing
    created_at = Column(DateTime, server_default=func.now())

    # ========================================================================
    # RELATIONSHIPS - Links to other tables
    # ========================================================================
    
    # Many-to-One: Many Shifts belong to one Worker
    # relationship(\"Worker\"): Link to Worker model class
    # back_populates=\"shifts\": Bidirectional - Worker.shifts links back
    # Allows accessing the worker: shift.worker → returns Worker object
    worker = relationship("Worker", back_populates="shifts")
