"""create_users_and_metrics_tables

Revision ID: 4706429fab17
Revises: e6f6ba83c2dc
Create Date: 2026-02-13 08:48:53.133710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4706429fab17'
down_revision: Union[str, None] = 'e6f6ba83c2dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shifts_id', table_name='shifts')
    op.drop_index('ix_shifts_worker_id', table_name='shifts')
    op.drop_table('shifts')
    op.drop_index('ix_workers_email', table_name='workers')
    op.drop_index('ix_workers_id', table_name='workers')
    op.drop_index('ix_workers_name', table_name='workers')
    op.drop_table('workers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workers',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('workers_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='workers_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_workers_name', 'workers', ['name'], unique=False)
    op.create_index('ix_workers_id', 'workers', ['id'], unique=False)
    op.create_index('ix_workers_email', 'workers', ['email'], unique=False)
    op.create_table('shifts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('earnings', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('predicted_earnings', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name='shifts_worker_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='shifts_pkey')
    )
    op.create_index('ix_shifts_worker_id', 'shifts', ['worker_id'], unique=False)
    op.create_index('ix_shifts_id', 'shifts', ['id'], unique=False)
    # ### end Alembic commands ###
